name: Deploy React Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache para node_modules (acelera muchísimo el pipeline )
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('react-frontend-app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Instalar dependencias en la carpeta frontend
      - name: Install dependencies
        working-directory: ./react-frontend-app
        run: npm ci

      # # (OPCIONAL) Ejecutar tests si existe script "test"
      # - name: Run tests
      #   working-directory: ./react-frontend-app
      #   if: contains(steps.check_scripts.outputs.has_test, 'true')
      #   run: npm test -- --watch=false

      # Build de producción
      - name: Build project
        working-directory: ./react-frontend-app
        run: npm run build

      # Crear archivo ZIP con el dist
      - name: Create deployment package
        run: |
          cd react-frontend-app
          zip -r dist.zip dist

      # Subir dist al droplet
      - name: Upload frontend package
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "react-frontend-app/dist.zip"
          target: "/root/laravel_react_js_app"

      # Reemplazar dist en el servidor
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /root/laravel_react_js_app

            # eliminar dist anterior
            rm -rf react-frontend-app/dist

            # descomprimir nueva versión
            unzip dist.zip -d react-frontend-app
            rm dist.zip

            # reiniciar nginx (si estuviera en un contenedor)
            docker compose restart nginx || true
