name: Deploy React Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache npm
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Instalar dependencias desde la raíz del repo
      - name: Install dependencies
        run: npm ci

      # # Ejecutar tests si existen.
      # - name: Run tests
      #   run: npm test -- --watch=false
      #   continue-on-error: true # opcional si no tienes test

      # Build de producción
      - name: Build project
        run: npm run build

      # Crear ZIP del dist
      - name: Create deployment package
        run: zip -r dist.zip dist

      # Subir dist.zip al droplet
      - name: Upload frontend package
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "dist.zip"
          target: "/root/laravel_react_js_app"

      # Reemplazar dist en el servidor
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /root/laravel_react_js_app

            # eliminar dist anterior
            rm -rf react-frontend-app/dist

            # descomprimir nueva versión
            unzip dist.zip -d react-frontend-app
            rm dist.zip

            # reiniciar nginx si está en docker
            docker compose restart nginx || true
